import type { LucideIcon } from "lucide-react";

export interface QuickPrompt {
  id: string;
  title: string;
  description: string;
  iconName: string;
  prompt: string;
  category: "analysis" | "data" | "visualization" | "export" | "general";
}

export const QUICK_PROMPTS: QuickPrompt[] = [
  {
    id: "forest-analysis",
    title: "Analyse forestière",
    description: "Analyser les peuplements forestiers et essences",
    iconName: "Layers",
    prompt: "Analyse les peuplements forestiers de la zone d'étude. Donne-moi les types d'essences présentes, leur répartition, et les surfaces par type de peuplement.",
    category: "analysis",
  },
  {
    id: "ndvi-analysis",
    title: "Santé forestière NDVI",
    description: "Analyser la santé des arbres avec NDVI",
    iconName: "Globe",
    prompt: "Charge le NDVI Sentinel-2 et analyse la santé de la forêt. Identifie les zones de stress hydrique, les zones saines, et les zones nécessitant une attention particulière.",
    category: "analysis",
  },
  {
    id: "soil-rum-analysis",
    title: "Analyse sol RUM",
    description: "Analyser la Réserve Utile Maximale des sols",
    iconName: "BarChart3",
    prompt: "Charge la Réserve Utile Maximale des sols (RUM) et analyse la capacité de rétention en eau. Identifie les zones favorables à la plantation et les zones à risque de sécheresse.",
    category: "analysis",
  },
  {
    id: "inventory-grid",
    title: "Grille d'inventaire",
    description: "Créer une grille d'inventaire forestier",
    iconName: "BarChart3",
    prompt: "Crée une grille d'inventaire forestier de 250m x 250m sur la couche forestière sélectionnée, avec centroïdes pour les relevés terrain.",
    category: "data",
  },
  {
    id: "geology-analysis",
    title: "Analyse géologique",
    description: "Analyser la carte géologique BRGM",
    iconName: "Search",
    prompt: "Charge la carte géologique BRGM et analyse le sous-sol de la zone d'étude. Identifie les types de roches, les zones sismiques, et les mines/carrières.",
    category: "analysis",
  },
  {
    id: "topography-analysis",
    title: "Analyse topographique",
    description: "Analyser le SCAN25 et MNT IGN",
    iconName: "Globe",
    prompt: "Charge le SCAN25 IGN et le MNT pour analyser la topographie. Identifie les pentes, l'exposition, et les zones favorables à l'exploitation forestière.",
    category: "analysis",
  },
  {
    id: "export-forest-stats",
    title: "Export forestier",
    description: "Exporter les statistiques forestières en CSV",
    iconName: "FileText",
    prompt: "Exporte les statistiques des peuplements forestiers dans un fichier CSV avec les essences, surfaces, et données de structure.",
    category: "export",
  },
  {
    id: "forest-fire-risk",
    title: "Risque feu forestier",
    description: "Analyser le risque de feu avec MODIS",
    iconName: "Zap",
    prompt: "Charge le détecteur de feu MODIS et analyse les zones à risque d'incendie forestier dans la zone d'étude.",
    category: "analysis",
  },
  {
    id: "load-sentinel",
    title: "Image Sentinel-2 réelle",
    description: "Charger les bandes Sentinel-2 d'une zone (STAC)",
    iconName: "Globe",
    prompt: "Charge l'image Sentinel-2 la moins nuageuse sur l'emprise de la zone d'étude (bandes rouge et proche infrarouge) via loadSatelliteBands.",
    category: "data",
  },
  {
    id: "change-detection",
    title: "Détection de changement",
    description: "Carte de changement dNDVI multi-dates",
    iconName: "Search",
    prompt: "Calcule le NDVI à deux dates, fais la différence (computeRasterDifference) puis classe le changement en niveaux de sévérité (classifyChange dndvi).",
    category: "analysis",
  },
  {
    id: "zonal-stats",
    title: "Stats par zone",
    description: "NDVI moyen par parcelle/polygone",
    iconName: "BarChart3",
    prompt: "Calcule les statistiques zonales (moyenne, min, max) du NDVI pour chaque entité de la couche de polygones sélectionnée (zonalStatistics).",
    category: "analysis",
  },
  {
    id: "classify-veg",
    title: "Classes de végétation",
    description: "Classer un NDVI en classes thématiques",
    iconName: "Layers",
    prompt: "Applique une classification thématique au raster NDVI en classes de végétation (classifyRaster ndvi_vegetation).",
    category: "visualization",
  },
  {
    id: "run-dossier",
    title: "Dossier territorial 1-clic",
    description: "Urbanisme / risques / forêt / environnement",
    iconName: "Layers",
    prompt: "Déroule le dossier territorial 'urbanisme' (runDossier) : charge les couches et applique les symbologies institutionnelles automatiquement.",
    category: "data",
  },
  {
    id: "suitability",
    title: "Analyse de site",
    description: "Carte d'aptitude multi-critères pondérés",
    iconName: "Search",
    prompt: "Réalise une analyse d'aptitude (suitabilityAnalysis) en combinant pente, occupation du sol et distances avec des poids, pour trouver les zones les plus favorables.",
    category: "analysis",
  },
  {
    id: "hotspots",
    title: "Hotspots / densité",
    description: "Carte de chaleur d'une couche de points",
    iconName: "Zap",
    prompt: "Génère une carte de chaleur (hotspotAnalysis) des points de la couche sélectionnée pour révéler les zones de forte concentration.",
    category: "analysis",
  },
  {
    id: "buffer",
    title: "Zone tampon",
    description: "Buffer autour d'entités (ex: 500 m)",
    iconName: "Search",
    prompt: "Crée une zone tampon de 500 m autour des entités de la couche sélectionnée (bufferLayer).",
    category: "analysis",
  },
  {
    id: "print-layout",
    title: "Planche cartographique",
    description: "Mise en page pro PNG/PDF (template)",
    iconName: "FileText",
    prompt: "Génère une planche cartographique professionnelle (titre, carte, légende, échelle) au format paysage et exporte-la en PNG (exportPrintLayout, template a4_paysage_pro).",
    category: "export",
  },
  {
    id: "atlas",
    title: "Atlas PDF multi-pages",
    description: "1 page par entité (communes/parcelles)",
    iconName: "FileText",
    prompt: "Génère un atlas PDF avec une page par entité de la couche de couverture sélectionnée (exportAtlas).",
    category: "export",
  },
  {
    id: "auto-improve-map",
    title: "Auto-améliorer la carte",
    description: "Boucle vision : rendu critiqué par un VLM",
    iconName: "Globe",
    prompt: "Améliore automatiquement la mise en page de la carte courante : rends-la, fais-la critiquer par le modèle vision et corrige jusqu'à un score complet (autoImproveLayout).",
    category: "visualization",
  },
  {
    id: "diagnostic-report",
    title: "Rapport de diagnostic",
    description: "Synthèse markdown narrée",
    iconName: "FileText",
    prompt: "Génère un rapport de diagnostic végétation au format markdown à partir des résultats d'analyse (generate_report diagnostic_vegetation).",
    category: "export",
  },
  {
    id: "segment-sam",
    title: "Segmentation IA (SAM)",
    description: "Détecter bâti / eau / parcelles sur une image",
    iconName: "Search",
    prompt: "Segmente automatiquement l'orthophoto chargée avec Segment Anything (segmentRasterWithSAM) pour extraire les objets (bâti, eau, parcelles) en polygones.",
    category: "analysis",
  },
];
